filter:
  dependency_paths:
    - ol7/

build:
  nodes:
    node-with-auto-setup:
      dependencies:          # This needs to be the section name like "tests", "dependencies", or "project_setup"
        override:
          - true
